[package]
name = "hy543-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = "0.8.0"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"